[tasks.run]
command = "cargo"
args = ["run", "--bin", "${@}"]

[tasks.test]
command = "cargo"
args = ["atcoder", "test", "${@}"]

[tasks.expand]
script = "expand.py --bin ${@}"

[tasks.submit]
dependencies = ["expand"]
command = "cargo"
args = ["atcoder", "submit", "${@}"]

[tasks.pretest]
command = "cargo"
args = ["test"]

[tasks.readme]
script = """
cargo readme > README.md
git add README.md
git commit -m "update README by cargo-readme"
"""

[tasks.push]
dependencies = ["pretest", "readme"]
script = """
git push origin master
"""