[tasks.run]
command = "cargo"
args = ["run", "--bin", "${@}"]

[tasks.test]
command = "cargo"
args = ["atcoder", "test", "${@}"]

[tasks.expand]
script = "expand.py --bin ${@}"

[tasks.submit]
dependencies = ["expand"]
command = "cargo"
args = ["atcoder", "submit", "${@}"]

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.pretest]
dependencies = ["format"]
command = "cargo"
args = ["test"]

[tasks.readme]
script = """
cargo readme > README.md

lines=$(git diff --name-only | wc -l)
if [ $lines -eq 1 ]; then
    git add README.md
    git commit -m "update README by cargo-readme"
fi
"""

[tasks.cargo-atcoder-config]
command = "cp"
args = ["./cargo-atcoder.toml", "${HOME}/.config/cargo-atcoder.toml"]

[tasks.push]
dependencies = ["tasks.cargo-atcoder-config", "pretest", "readme"]
script = """
git push origin master
"""