[tasks.run]
command = "cargo"
args = ["run", "--bin", "${@}"]

[tasks.test]
command = "cargo"
args = ["atcoder", "test", "${@}"]

[tasks.expand]
script = "expand.py --bin ${@}"

[tasks.submit]
dependincies = ["expand"]
command = "cargo"
args = ["atcoder", "submit", "${@}"]

[tasks.push]
script = """
#!/bin/bash
set -eu
cargo readme > README.md
git add README.md
git commit -m "update README by cargo-readme"
git push origin master
"""